# Generated by Django 4.2.4 on 2023-08-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_id", models.IntegerField()),
                ("vehicle_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("address", models.CharField(max_length=50)),
                ("cargo_tonnage", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("pickup_point", "Pickup Point"),
                            ("drop_off_point", "Drop Off Point"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("driver", "Driver"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_name", models.CharField(max_length=100)),
                (
                    "trips",
                    models.ManyToManyField(
                        related_name="vehicles", to="trip_details.trip"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="vehicles", to="trip_details.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trip",
            name="done_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trip_details.user"
            ),
        ),
    ]
